language: python
dist: xenial
sudo: required

before_install:
  - sudo apt-get install -y -q openmpi-bin libopenmpi-dev
  - pip install pytest-cov isort black

install:
 - pip install -e .

script:
 - black --check src/data
 - isort -rc --diff src/ tests/
 - py.test --cov=./

after_success:
 - pip install codecov; codecov;
