language: python
dist: xenial
sudo: required

before_install:
  - sudo apt-get install -y -q openmpi-bin libopenmpi-dev
  - pip install --upgrade pip
  - pip install pytest-cov isort black

install:
 - pip install -e .

script:
 - black --check gcn_prot/data gcn_prot/ tests
 - isort -rc --diff --check-only gcn_prot/ tests/
 - py.test --cov=./

after_success:
 - pip install codecov; codecov;
